name: fazseg-app
dependencies:
  - python=3.6.13
  - pip==21.1.2
  - pip:
    - numpy==1.17.3
    - Pillow==6.2.0
    - pandas==0.25.1
    - scikit-learn==0.19.0
    - tqdm==4.40.2
    - iterative-stratification==0.1.6
    - gdown==3.13.0
    - torch==1.3.0
    - torchvision==0.4.1
    - opencv-python==4.1.1.26
    - streamlit==0.83.0
    - imgaug==0.3.0
    - efficientnet-pytorch==0.5.0






